### ISSUE TITLE
Duplicated information for terraform

### ISSUE THREAD

**Issue by sebastian-luna-valero** [usegalaxy-eu/terraform#14]
Hello,

There seems to be a good overlap between
* the `tf` folder in `pulsar-deployment` repository: https://github.com/usegalaxy-eu/pulsar-deployment/tree/public/tf
* the `tf` folder in the `pulsar-infrastructure` repository: https://github.com/usegalaxy-eu/pulsar-infrastructure/tree/master/tf

The  `pulsar-deployment` repository is more up to date, but the docs in https://pulsar-network.readthedocs.io/ point to the `pulsar-infrastructure` repository.

Sorry if I am missing something obvious, could you please confirm what's the correct way to go?

xref: https://github.com/usegalaxy-eu/vgcn/issues/75

**Comment by sanjaysrikakulam** [comment]
Hi!

The `pulsar-deployment` repo is the currently maintained one. I think @mtangaro was working on the new documentation or updating the old one. 

Sorry for the confusion. Soon, the docs will be updated.

**Comment by mtangaro** [comment]
@sebastian-luna-valero please just refer to the pulsar-deployment repository.
Probably, we should archive old Pulsar Network old repositories (@mira-miracoli, @bgruening):
- https://github.com/usegalaxy-eu/pulsar-infrastructure-playbook
- https://github.com/usegalaxy-eu/pulsar-infrastructure

**Comment by sebastian-luna-valero** [comment]
Will do, thanks both!
