### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by mira-miracoli** [usegalaxy-eu/terraform#7]
I would like to rename this repo, becuase terraform is not very clear.
My suggestion would be

**pulsar-deployment**

I think it gets more clear then what its purpose is.

The work-flow for people who want to create their pulsar endpoint would be:

1. Fork the repo
2. change the vars in terraform and in the ansible directory accordingly
3. request RabbitMQ user/vhost with password from usegalaxy.eu
4. launch the instance by applying terraform with the secrets: condor password, amqp string and path to their private key.
```bash
terraform apply -var "pvt_key=~/.ssh/theKey" -var "condor_pass=theirCondorPW" -var "mq_string=pyamqp://their_new_pulsar:thePassword@mq.galaxyproject.eu:5671//pulsar/their_new_pulsar?ssl=1"
```
The advantage is, that Pulsar can be deployed in one step and the secrets don't live in a terraform state file, they can be stored in a vault or password manager instead.

**Comment by mira-miracoli** [comment]
ping @bgruening @mtangaro

**Comment by bgruening** [comment]
How would "our fork" of the repo be named where we keep track of the pulsar nodes that we maintain? `pulsar-deployment-freiburg`?

**Comment by mira-miracoli** [comment]
That would be a good name, I think

**Comment by mtangaro** [comment]
The name is fine for me, too. Probably I would name forks with "de01, it01,..". But of course this is up to who has to manage the fork
